[package]
name = "rust_lexer"
version = "0.1.0"
authors = ["程勋德 <chengxd@300624.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
